# Trident Documentation Workflow
name: trident-docs

on:
    push:
        branches:
            - main

jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python 
              uses: actions/setup-python@v2
              with:
                python-version: '3.7'

            - name: Build Trident Documentation
              run: |
                make install
                cd docs && make html
                cd .. && mkdir public && mv ./docs/build/html/* ./public

            - name: Deploy Trident Documentation
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public
